version: 0.2

phases:
  install:
    commands:
      - systemctl stop amazon-ssm-agent
      - dnf update -y
      - dnf install -y curl unzip
      - systemctl start amazon-ssm-agent
      - curl -qL -o packer.zip https://releases.hashicorp.com/packer/1.10.4/packer_1.10.4_linux_amd64.zip
      - unzip packer.zip
      - sudo mv packer /usr/local/bin/
  build:
    commands:
      - packer version
      - cd infrastructure/packer
      - packer init .
      - packer build backend-ami.pkr.hcl

artifacts:
  files:
    - build-metadata.json
    - infrastructure/packer/**/*
    - appspec.yml
    - scripts/**/*
  name: GoldenAmiArtifact
