version: 0.2

phases:
  install:
    commands:
      - echo "Installing Packer..."
      - curl -qL -o packer.zip https://releases.hashicorp.com/packer/1.10.4/packer_1.10.4_linux_amd64.zip
      - unzip packer.zip
      - sudo mv packer /usr/local/bin/
  build:
    commands:
      - export PATH=$PATH:/usr/local/bin
      - echo "Using custom AL2023 CodeBuild image"
      - packer version
      - cd infrastructure/packer
      - packer init .
      - packer build backend-ami.pkr.hcl
