version: 0.2

phases:
  install:
    commands:
      - curl -fsSL https://releases.hashicorp.com/packer/1.9.4/packer_1.9.4_linux_amd64.zip -o packer.zip
      - unzip packer.zip
      - mv packer /usr/local/bin/
  build:
    commands:
      - cd infrastructure/packer
      - packer init .
      - packer build .
artifacts:
  files:
    - packer-manifest.json
