version: 0.2

env:
  variables:
    PACKER_VERSION: "1.14.3"
    AWS_REGION: "us-east-1"
    ECR_REPO: "backend-docker-build"

phases:
  install:
    commands:
      - "echo Installing required tools..."
      - "dnf install -y unzip jq awscli curl"
      - "curl -fsSL https://s3.amazonaws.com/session-manager-downloads/plugin/latest/linux_64bit/session-manager-plugin.rpm -o ssm.rpm"
      - "rpm -i ssm.rpm || true"
      - "session-manager-plugin --version || true"

  pre_build:
    commands:
      - "echo Downloading Packer..."
      - "curl -fsSL https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip -o packer.zip"
      - "unzip -o packer.zip"
      - "chmod +x packer"
      - "mv packer /usr/local/bin/packer"
      - "packer version"
      - "export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)"
      - "export IMAGE_TAG=$(aws ecr describe-images --repository-name ${ECR_REPO} --region ${AWS_REGION} --query 'sort_by(imageDetails,&imagePushedAt)[-1].imageTags[0]' --output text || echo 'latest')"
      - "echo IMAGE_TAG=$IMAGE_TAG"
      - "cd infrastructure/packer"

  build:
    commands:
      - "echo Building AMI with Packer..."
      - "packer build -machine-readable -var aws_region=${AWS_REGION} -var aws_account_id=${AWS_ACCOUNT_ID} -var project_name=${PROJECT_NAME} -var ecr_repo=${ECR_REPO} -var docker_image_tag=${IMAGE_TAG} -var instance_profile_name=${INSTANCE_PROFILE_NAME} -var vpc_id=${VPC_ID} -var subnet_id=${SUBNET_ID} backend-ami.pkr.hcl 2>&1 | tee packer-output.log"
      - "if ! grep -q 'artifact,0,id' packer-output.log; then echo ERROR: Packer build failed or AMI not created; exit 1; fi"

  post_build:
    commands:
      - "echo Extracting AMI ID from Packer output..."
      - "AMI_ID=$(grep 'artifact,0,id' infrastructure/packer/packer-output.log | tail -1 | cut -d',' -f6 | cut -d':' -f2)"
      - "if [ -z '$AMI_ID' ]; then echo ERROR: AMI_ID is empty, build failed; exit 1; fi"
      - "echo '{\"amiId\":\"'$AMI_ID'\",\"imageTag\":\"'$IMAGE_TAG'\"}' > ami-info.json"
      - "cat ami-info.json"

artifacts:
  files:
    - "ami-info.json"
