version: 0.2

env:
  parameter-store:
    PACKER_GITHUB_API_TOKEN: /ci/github/token
    
  variables:
    PACKER_VERSION: "1.14.3"
    PACKER_LOG: "1"
    PACKER_LOG_PATH: "/tmp/packer.log"
    AWS_ACCOUNT_ID: "734649603753"
    PACKER_PLUGIN_PATH: "/root/.packer.d/plugins"

phases:
  install:
    commands:
      - curl -O https://s3.amazonaws.com/session-manager-downloads/plugin/latest/linux_64bit/session-manager-plugin.rpm
      - rpm -i session-manager-plugin.rpm
      - session-manager-plugin --version
      - "echo Verifying CodeBuild environment"
      - "cat /etc/os-release"
      - "which curl"
      - "which unzip"
      - "which jq || true"

  pre_build:
    commands:
      - "echo Installing Packer"
      - "curl -fsSL https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip -o packer.zip"
      - "unzip -o packer.zip"
      - "chmod +x packer"
      - "./packer version"
      - "chmod +x infrastructure/packer/scripts/*.sh"
      - "export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)"
      - "export IMAGE_TAG=$(aws ecr describe-images --repository-name backend-docker-build --region us-east-1 --query 'sort_by(imageDetails,&imagePushedAt)[-1].imageTags[0]' --output text)"
      - 'if [ -z "$IMAGE_TAG" ]; then echo "ERROR: IMAGE_TAG is empty! Check ECR permissions."; exit 1; fi'
      - "export ECR_REPO=backend-docker-build"
      - "cd infrastructure/packer"

  build:
    commands:
      # ===== DEBUGGING (ADDED ONLY) =====
      - "echo AWS_ACCOUNT_ID=${AWS_ACCOUNT_ID}"
      - "echo PROJECT_NAME=${PROJECT_NAME}"
      - "echo ECR_REPO=${ECR_REPO}"
      - "echo IMAGE_TAG=${IMAGE_TAG}"
      - "echo INSTANCE_PROFILE_NAME=${INSTANCE_PROFILE_NAME}"
      - "echo VPC_ID=${VPC_ID}"
      - "echo SUBNET_ID=${SUBNET_ID}"
      - "pwd"
      - "ls -la"
      - "ls -la ../../"
      # ===== END DEBUGGING =====

      - "../../packer init backend-ami.pkr.hcl"
      - "../../packer validate -var aws_region=us-east-1 -var aws_account_id=${AWS_ACCOUNT_ID} -var project_name=${PROJECT_NAME} -var ecr_repo=${ECR_REPO} -var docker_image_tag=${IMAGE_TAG} -var instance_profile_name=${INSTANCE_PROFILE_NAME} -var vpc_id=${VPC_ID} -var subnet_id=${SUBNET_ID} backend-ami.pkr.hcl"
      - "../../packer build -var aws_region=us-east-1 -var aws_account_id=${AWS_ACCOUNT_ID} -var project_name=${PROJECT_NAME} -var ecr_repo=${ECR_REPO} -var docker_image_tag=${IMAGE_TAG} -var instance_profile_name=${INSTANCE_PROFILE_NAME} -var vpc_id=${VPC_ID} -var subnet_id=${SUBNET_ID} backend-ami.pkr.hcl || (cat /tmp/packer.log && exit 1)"

  post_build:
    commands:
      - "cd ../.."
      - "export AMI_ID=$(jq -r '.builds[0].artifact_id' infrastructure/packer/packer-manifest.json | cut -d: -f2)"
      - "printf '{\"amiId\":\"%s\",\"imageTag\":\"%s\"}' \"$AMI_ID\" \"$IMAGE_TAG\" > ami-info.json"
      - "cat ami-info.json"

artifacts:
  files:
    - ami-info.json
