version: 0.2

env:
  parameter-store:
    PACKER_GITHUB_API_TOKEN: /ci/github/token

  variables:
    PACKER_VERSION: "1.14.3"
    PACKER_LOG: "1"
    PACKER_LOG_PATH: "/tmp/packer.log"
    AWS_REGION: "us-east-1"
    ECR_REPO: "backend-docker-build"

phases:
  install:
    commands:
      - "echo Installing base tools"
      - "dnf install -y unzip jq awscli"
      - "aws --version"
      - "jq --version"
      - "curl -fsSL https://s3.amazonaws.com/session-manager-downloads/plugin/latest/linux_64bit/session-manager-plugin.rpm -o ssm.rpm"
      - "rpm -i ssm.rpm"
      - "session-manager-plugin --version"

  pre_build:
    commands:
      - "echo Installing Packer ${PACKER_VERSION}"
      - "curl -fsSL https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip -o packer.zip"
      - "unzip -o packer.zip"
      - "chmod +x packer"
      - "mv packer /usr/local/bin/packer"
      - "packer version"
      - "export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)"
      - "export IMAGE_TAG=$(aws ecr describe-images --repository-name ${ECR_REPO} --region ${AWS_REGION} --query 'sort_by(imageDetails,&imagePushedAt)[-1].imageTags[0]' --output text)"
      - 'if [ -z "$IMAGE_TAG" ] || [ "$IMAGE_TAG" = "None" ]; then echo "ERROR: IMAGE_TAG not found in ECR"; exit 1; fi'
      - "echo Using IMAGE_TAG=${IMAGE_TAG}"
      - "cd infrastructure/packer"
      - "ls -la"

  build:
    commands:
      - "echo Initializing Packer"
      - "packer init backend-ami.pkr.hcl"
      - "packer validate -var aws_region=${AWS_REGION} -var aws_account_id=${AWS_ACCOUNT_ID} -var project_name=${PROJECT_NAME} -var ecr_repo=${ECR_REPO} -var docker_image_tag=${IMAGE_TAG} -var instance_profile_name=${INSTANCE_PROFILE_NAME} -var vpc_id=${VPC_ID} -var subnet_id=${SUBNET_ID} backend-ami.pkr.hcl"
      - "packer build -var aws_region=${AWS_REGION} -var aws_account_id=${AWS_ACCOUNT_ID} -var project_name=${PROJECT_NAME} -var ecr_repo=${ECR_REPO} -var docker_image_tag=${IMAGE_TAG} -var instance_profile_name=${INSTANCE_PROFILE_NAME} -var vpc_id=${VPC_ID} -var subnet_id=${SUBNET_ID} backend-ami.pkr.hcl || (echo Packer build failed && cat /tmp/packer.log && exit 1)"

  post_build:
    commands:
      - "cd ../.."
      - 'if [ -f infrastructure/packer/packer-manifest.json ]; then export AMI_ID=$(jq -r ".builds[0].artifact_id" infrastructure/packer/packer-manifest.json | cut -d: -f2); printf "{\"amiId\":\"%s\",\"imageTag\":\"%s\"}" "$AMI_ID" "$IMAGE_TAG" > ami-info.json; cat ami-info.json; else echo "ERROR: packer-manifest.json not found"; exit 1; fi'

artifacts:
  files:
    - ami-info.json
