version: 0.2

env:
  variables:
    PACKER_VERSION: "1.10.0"
    PACKER_LOG: "1"

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - apt-get update -y
      - apt-get install -y wget unzip jq
      - echo "Installing AWS Session Manager Plugin..."
      - curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
      - dpkg -i session-manager-plugin.deb || apt-get install -f -y
  
  pre_build:
    commands:
      - echo "=== AMI Build Started ==="
      - wget -q https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip
      - unzip -q packer_${PACKER_VERSION}_linux_amd64.zip
      - chmod +x packer
      - ./packer version
      - chmod +x infrastructure/packer/scripts/*.sh
      - export LATEST_TAG=$(aws ecr describe-images --repository-name backend --region us-east-1 --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageTags[0]' --output text 2>/dev/null || echo "latest")
      - export IMAGE_TAG=${LATEST_TAG}
      - export ECR_REPO="backend"
      - cd infrastructure/packer
  
  build:
    commands:
      - echo "Initializing Packer..."
      - ../../packer init backend-ami.pkr.hcl
      - echo "Validating Packer template..."
      - ../../packer validate -var "aws_region=us-east-1" -var "aws_account_id=${AWS_ACCOUNT_ID}" -var "project_name=${PROJECT_NAME}" -var "ecr_repo=${ECR_REPO}" -var "docker_image_tag=${IMAGE_TAG}" -var "instance_profile_name=${INSTANCE_PROFILE_NAME}" -var "vpc_id=${VPC_ID}" -var "subnet_id=${SUBNET_ID}" backend-ami.pkr.hcl
      - echo "Building AMI with VERBOSE logging..."
      - PACKER_LOG=1 ../../packer build -var "aws_region=us-east-1" -var "aws_account_id=${AWS_ACCOUNT_ID}" -var "project_name=${PROJECT_NAME}" -var "ecr_repo=${ECR_REPO}" -var "docker_image_tag=${IMAGE_TAG}" -var "instance_profile_name=${INSTANCE_PROFILE_NAME}" -var "vpc_id=${VPC_ID}" -var "subnet_id=${SUBNET_ID}" backend-ami.pkr.hcl 2>&1 | tee packer-build.log
  
  post_build:
    commands:
      - echo "Checking if build succeeded..."
      - cd ../..
      - test -f infrastructure/packer/packer-manifest.json || (echo "Build failed - no manifest created" && cat infrastructure/packer/packer-build.log && exit 1)
      - export AMI_ID=$(jq -r '.builds[0].artifact_id' infrastructure/packer/packer-manifest.json | cut -d':' -f2)
      - echo "AMI ID ${AMI_ID}"
      - echo "{\"amiId\":\"${AMI_ID}\",\"imageTag\":\"${IMAGE_TAG}\",\"buildDate\":\"$(date -u +'%Y-%m-%dT%H:%M:%SZ')\"}" > ami-info.json
