version: 0.2

env:
  variables:
    PACKER_VERSION: "1.10.0"

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - apt-get update
      - apt-get install -y wget unzip jq
  
  pre_build:
    commands:
      - echo "=== AMI Build Started ==="
      - echo "Installing Packer..."
      - wget -q https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip
      - unzip -q packer_${PACKER_VERSION}_linux_amd64.zip
      - chmod +x packer
      - ./packer version
      - echo "Current directory:"
      - pwd
      - echo "Listing files:"
      - ls -la
      - echo "Getting latest Docker image tag from ECR..."
      - LATEST_TAG=$(aws ecr describe-images --repository-name backend --region us-east-1 --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageTags[0]' --output text 2>/dev/null || echo "latest")
      - echo "Latest image tag: ${LATEST_TAG}"
      - export IMAGE_TAG=${LATEST_TAG}
      - export ECR_REPO="backend"
      - echo "Checking if packer directory exists..."
      - ls -la infrastructure/packer/ || echo "Directory not found!"
      - cd infrastructure/packer
  
  build:
    commands:
      - echo "Initializing Packer..."
      - ../../packer init backend-ami.pkr.hcl
      - echo "Validating Packer template..."
      - ../../packer validate -var "aws_region=us-east-1" -var "aws_account_id=${AWS_ACCOUNT_ID}" -var "project_name=${PROJECT_NAME}" -var "ecr_repo=${ECR_REPO}" -var "docker_image_tag=${IMAGE_TAG}" -var "instance_profile_name=${INSTANCE_PROFILE_NAME}" -var "vpc_id=${VPC_ID}" -var "subnet_id=${SUBNET_ID}" backend-ami.pkr.hcl
      - echo "Building AMI (this takes 15-20 minutes)..."
      - ../../packer build -var "aws_region=us-east-1" -var "aws_account_id=${AWS_ACCOUNT_ID}" -var "project_name=${PROJECT_NAME}" -var "ecr_repo=${ECR_REPO}" -var "docker_image_tag=${IMAGE_TAG}" -var "instance_profile_name=${INSTANCE_PROFILE_NAME}" -var "vpc_id=${VPC_ID}" -var "subnet_id=${SUBNET_ID}" backend-ami.pkr.hcl
  
  post_build:
    commands:
      - echo "Extracting AMI ID..."
      - AMI_ID=$(jq -r '.builds[0].artifact_id' packer-manifest.json | cut -d':' -f2)
      - echo "AMI created: ${AMI_ID}"
      - cd ../..
      - echo "{\"amiId\":\"${AMI_ID}\",\"imageTag\":\"${IMAGE_TAG}\",\"buildDate\":\"$(date -u +'%Y-%m-%dT%H:%M:%SZ')\"}" > ami-info.json
      - cat ami-info.json
      - echo "=== AMI Build Complete ==="

artifacts:
  files:
    - ami-info.json
