version: 0.2

phases:
  install:
    commands:
      - echo "WHOAMI"
      - whoami
      - echo "OS RELEASE"
      - cat /etc/os-release || true
      - echo "PACKAGE MANAGER"
      - which yum || true
      - which dnf || true
      - which apt-get || true
      - echo "REPO LIST"
      - yum repolist || true
      - dnf repolist || true
