version: 0.2

env:
  variables:
    REPOSITORY_URI: "734649603753.dkr.ecr.us-east-1.amazonaws.com/backend-docker-build"

phases:
  pre_build:
    commands:
      - echo "### PIPELINE IS USING THE CORRECT BUILDSPEC ###"
      - env | sort
      - echo "Logging in to Amazon ECR..."
      - echo "AWS_REGION=$AWS_REGION"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI

      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:-latest}
      - BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')

      - echo "Build variables:"
      - echo "  IMAGE_TAG=${IMAGE_TAG}"
      - echo "  BUILD_DATE=${BUILD_DATE}"

  build:
    commands:
      - echo "Build started on $(date)"
      - docker build -t backend:${IMAGE_TAG} .
      - docker tag backend:${IMAGE_TAG} ${REPOSITORY_URI}:${IMAGE_TAG}
      - docker tag backend:${IMAGE_TAG} ${REPOSITORY_URI}:latest

  post_build:
    commands:
      - echo "Pushing Docker images..."
      - docker push ${REPOSITORY_URI}:${IMAGE_TAG}
      - docker push ${REPOSITORY_URI}:latest

      - echo "Writing build metadata..."
      - |
        cat > build-metadata.json <<EOF
        {
          "imageUri": "${REPOSITORY_URI}:latest",
          "imageTag": "${IMAGE_TAG}",
          "commitHash": "${COMMIT_HASH}",
          "buildDate": "${BUILD_DATE}",
          "region": "${AWS_REGION}",
          "repository": "${REPOSITORY_URI}"
        }
        EOF

      - cat build-metadata.json

artifacts:
  files:
    - build-metadata.json
    - infrastructure/packer/**/*
    - appspec.yml
    - scripts/**/*
  name: DockerBuildArtifact
